# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class Kkrtctl < Formula
  desc "kkrtctl is CLI to operate proving of EVM blocks"
  homepage "https://github.com/kkrt-labs/kakarot-controller"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kkrt-labs/kakarot-controller/releases/download/v0.1.1/kakarot-controller_0.1.1_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d15fe955bad6bffc2e2d114a9e5a1a708c77a26a8c42a347a45873fbded30538"

      def install
        bin.install "kkrtctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kkrt-labs/kakarot-controller/releases/download/v0.1.1/kakarot-controller_0.1.1_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "378763d93fa392a43d810b58acd3d843c3563c22568ebf23a8a9f1e6c5705328"

      def install
        bin.install "kkrtctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kkrt-labs/kakarot-controller/releases/download/v0.1.1/kakarot-controller_0.1.1_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "0934e52beca39568cc8d97e50736686f7b4a0faf017e627a4a50ae8c5bab08b0"

        def install
          bin.install "kkrtctl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kkrt-labs/kakarot-controller/releases/download/v0.1.1/kakarot-controller_0.1.1_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "c0a23a4b517109be83c5e7d8577676a01ffd73706c5110e448f49e69dbfe4659"

        def install
          bin.install "kkrtctl"
        end
      end
    end
  end
end
