# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/custom_download_strategy"
class Testci < Formula
  desc "kkrt is CLI to operate EVM block proving"
  homepage "https://github.com/kkrt-labs/test-ci"
  version "0.3.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kkrt-labs/test-ci/releases/download/v0.3.6/test-ci_0.3.6_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f05f358179e5c2e78055009833590c3d75c8c2f4d11349236215b1abf7c29926"

      def install
        bin.install "testci"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kkrt-labs/test-ci/releases/download/v0.3.6/test-ci_0.3.6_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "b383665463a252c1c0ecd640768e10255496e8065c261f0588fdc178c1dbecad"

      def install
        bin.install "testci"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kkrt-labs/test-ci/releases/download/v0.3.6/test-ci_0.3.6_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "fb866043b8173a6ad4cdb2f7460028da9530fae28d1e5ecc220cb15241373649"

        def install
          bin.install "testci"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kkrt-labs/test-ci/releases/download/v0.3.6/test-ci_0.3.6_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "58e956a675d5fce537e8fba49785170cc1470ff976f8bbcc9c8c52310eff17fb"

        def install
          bin.install "testci"
        end
      end
    end
  end
end
