# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zkpig < Formula
  desc "zkpig enables to generate ZK-EVM prover inputs for proving EVM blocks"
  homepage "https://github.com/kkrt-labs/zk-pig"
  version "0.7.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kkrt-labs/zk-pig/releases/download/v0.7.0/zk-pig_0.7.0_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "ef92fd7b19556e7580ef7522a47cf62fb249422013595afaa868ca356b9aea9c"

      def install
        bin.install "zkpig"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kkrt-labs/zk-pig/releases/download/v0.7.0/zk-pig_0.7.0_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "57076851e5e4a311e775b353056b3fca4b4199c98b87e5c0c753a73eab46f7f8"

      def install
        bin.install "zkpig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kkrt-labs/zk-pig/releases/download/v0.7.0/zk-pig_0.7.0_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "dff491e04b11c8e831512d43042fe5ff7b517bf46dce978cfaf9241783667904"

        def install
          bin.install "zkpig"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kkrt-labs/zk-pig/releases/download/v0.7.0/zk-pig_0.7.0_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "474cfa1f615792c493e305b0b9bb754e76fbe35dd5c5040f2fbd29366c75a190"

        def install
          bin.install "zkpig"
        end
      end
    end
  end
end
